services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: videosos-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    restart: unless-stopped

